version: '3.9'

# services:
#   app:
#     image: ${DOCKER_IMAGE}
#     build:
#       context: .
#     ports:
#       - "8000:8000"


services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
